"use client";

import { useEffect, useState } from "react";
import { useSession } from "next-auth/react";
import Header from "@/components/layout/Header";
import Link from "next/link";
import { formatDate } from "@/utils/helpers";

interface Report {
  id: string;
  title: string;
  periodStart: string;
  periodEnd: string;
  createdAt: string;
  generatedByName: string;
}

export default function ReportsPage() {
  const { data: session } = useSession();
  const [reports, setReports] = useState<Report[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedReport, setSelectedReport] = useState<any>(null);
  const [reportLoading, setReportLoading] = useState(false);

  useEffect(() => {
    fetch("/api/reports")
      .then((r) => r.json())
      .then((d) => {
        setReports(d);
        setLoading(false);
      })
      .catch(() => setLoading(false));
  }, []);

  async function loadReport(id: string) {
    setReportLoading(true);
    const res = await fetch(`/api/reports/${id}`);
    const data = await res.json();
    setSelectedReport(data);
    setReportLoading(false);
  }

  async function handleDelete(id: string) {
    if (!confirm("Delete this report?")) return;
    await fetch(`/api/reports/${id}`, { method: "DELETE" });
    setReports((prev) => prev.filter((r) => r.id !== id));
    if (selectedReport?.id === id) setSelectedReport(null);
  }

  const canGenerate = session?.user?.role === "ADMIN" || session?.user?.role === "ANALYST";

  return (
    <>
      <Header
        title="Reports"
        subtitle="Voice of Customer reports generated by AI"
        actions={
          canGenerate ? (
            <Link
              href="/dashboard/reports/new"
              className="px-4 py-2 bg-indigo-600 hover:bg-indigo-500 text-white text-sm font-medium rounded-lg transition"
            >
              + Generate Report
            </Link>
          ) : null
        }
      />

      <main className="flex-1 p-6">
        {loading ? (
          <div className="flex items-center justify-center h-64">
            <div className="w-8 h-8 border-2 border-indigo-500 border-t-transparent rounded-full animate-spin" />
          </div>
        ) : (
          <div className="grid grid-cols-3 gap-6 h-full">
            {/* Report list */}
            <div className="col-span-1 space-y-2">
              <h2 className="text-xs font-medium text-slate-500 uppercase tracking-wider mb-3">Saved Reports</h2>
              {reports.length === 0 ? (
                <div className="bg-slate-900 border border-slate-800 rounded-xl p-8 text-center">
                  <div className="text-3xl mb-2">📋</div>
                  <div className="text-sm text-slate-400">No reports yet</div>
                  {canGenerate && (
                    <Link
                      href="/dashboard/reports/new"
                      className="mt-3 inline-block text-xs text-indigo-400 hover:text-indigo-300"
                    >
                      Generate your first report →
                    </Link>
                  )}
                </div>
              ) : (
                reports.map((r) => (
                  <button
                    key={r.id}
                    onClick={() => loadReport(r.id)}
                    className={`w-full text-left bg-slate-900 border rounded-xl p-4 transition hover:border-indigo-700 ${
                      selectedReport?.id === r.id ? "border-indigo-500" : "border-slate-800"
                    }`}
                  >
                    <div className="text-sm font-medium text-white mb-1 line-clamp-2">{r.title}</div>
                    <div className="text-xs text-slate-500">
                      {formatDate(r.periodStart)} – {formatDate(r.periodEnd)}
                    </div>
                    <div className="text-xs text-slate-600 mt-1">By {r.generatedByName}</div>
                  </button>
                ))
              )}
            </div>

            {/* Report detail */}
            <div className="col-span-2">
              {reportLoading ? (
                <div className="flex items-center justify-center h-64">
                  <div className="w-6 h-6 border-2 border-indigo-500 border-t-transparent rounded-full animate-spin" />
                </div>
              ) : selectedReport ? (
                <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 space-y-6">
                  <div className="flex items-start justify-between">
                    <div>
                      <h2 className="text-lg font-semibold text-white">{selectedReport.title}</h2>
                      <div className="text-sm text-slate-400 mt-1">
                        {formatDate(selectedReport.periodStart)} – {formatDate(selectedReport.periodEnd)}
                      </div>
                    </div>
                    <div className="flex gap-2">
                      <button
                        onClick={() => window.print()}
                        className="px-3 py-1.5 text-xs bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-lg"
                      >
                        🖨️ Print/PDF
                      </button>
                      {session?.user?.role === "ADMIN" && (
                        <button
                          onClick={() => handleDelete(selectedReport.id)}
                          className="px-3 py-1.5 text-xs bg-red-950 hover:bg-red-900 text-red-400 rounded-lg"
                        >
                          Delete
                        </button>
                      )}
                    </div>
                  </div>

                  {/* Executive summary */}
                  <div>
                    <h3 className="text-xs font-medium text-slate-500 uppercase tracking-wider mb-3">Executive Summary</h3>
                    <div className="bg-slate-800/50 rounded-xl p-4 text-sm text-slate-200 leading-relaxed whitespace-pre-wrap">
                      {(selectedReport.contentJson as any)?.summary ?? "No summary available"}
                    </div>
                  </div>

                  {/* Stats */}
                  {(selectedReport.contentJson as any)?.stats && (
                    <div>
                      <h3 className="text-xs font-medium text-slate-500 uppercase tracking-wider mb-3">Statistics</h3>
                      <div className="grid grid-cols-3 gap-3">
                        <div className="bg-slate-800/50 rounded-xl p-4">
                          <div className="text-2xl font-bold text-white">
                            {(selectedReport.contentJson as any).stats.totalFeedback}
                          </div>
                          <div className="text-xs text-slate-400 mt-1">Total Feedback</div>
                        </div>
                        <div className="bg-slate-800/50 rounded-xl p-4">
                          <div className="text-2xl font-bold text-green-400">
                            {(selectedReport.contentJson as any).stats.sentimentBreakdown?.positive ?? 0}
                          </div>
                          <div className="text-xs text-slate-400 mt-1">Positive</div>
                        </div>
                        <div className="bg-slate-800/50 rounded-xl p-4">
                          <div className="text-2xl font-bold text-red-400">
                            {(selectedReport.contentJson as any).stats.sentimentBreakdown?.negative ?? 0}
                          </div>
                          <div className="text-xs text-slate-400 mt-1">Negative</div>
                        </div>
                      </div>
                    </div>
                  )}

                  {/* Top themes */}
                  {(selectedReport.contentJson as any)?.stats?.topThemes?.length > 0 && (
                    <div>
                      <h3 className="text-xs font-medium text-slate-500 uppercase tracking-wider mb-3">Top Themes</h3>
                      <div className="space-y-2">
                        {(selectedReport.contentJson as any).stats.topThemes.slice(0, 5).map((t: any) => (
                          <div key={t.name} className="flex items-center gap-3">
                            <span className="text-sm text-slate-300 capitalize w-32 truncate">{t.name}</span>
                            <div className="flex-1 bg-slate-800 rounded-full h-2">
                              <div
                                className="h-2 bg-indigo-500 rounded-full"
                                style={{
                                  width: `${Math.min(
                                    100,
                                    ((t.count /
                                      Math.max(
                                        ...(selectedReport.contentJson as any).stats.topThemes.map((x: any) => x.count)
                                      )) *
                                      100)
                                  )}%`,
                                }}
                              />
                            </div>
                            <span className="text-xs text-slate-500 w-6 text-right">{t.count}</span>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              ) : (
                <div className="flex flex-col items-center justify-center h-64 text-slate-500">
                  <div className="text-3xl mb-2">👈</div>
                  <div className="text-sm">Select a report to view</div>
                </div>
              )}
            </div>
          </div>
        )}
      </main>
    </>
  );
}
